import turtle
t=turtle.Turtle()
print("orig.pos:", t.position() )

t.pencolor("red")
t.width(10)
t.forward(300)
t.penup()
t.left(90)
t.forward(50)
t.left(90)
t.pendown()
t.width(5)
t.pencolor("blue")
t.forward(300)

def drawThickGreenLine():
    t.penup()
    x=t.xcor()
    y=t.ycor()
    print(x,y)
    t.goto(x-365, y-352)
    t.pendown()
    t.pencolor("green")
    t.setheading(90)
    t.forward(615)
drawThickGreenLine()
t.right(90)
t.forward(727)
t.right(90)
t.forward(618)
t.right(90)
t.forward(727)

t.penup()
t.goto(0,0)
t.pendown()
t.pencolor("cyan")
t.forward(200)
t.left(90)
t.forward(300)
t.left(146)
t.forward(357)

def drawRightTriangle():
    x=t.xcor()
    y=t.ycor()
    t.setheading(0)
    t.pendown()
    t.forward(90)
    t.right(90)
    t.forward(120)
    t.goto(x,y)
    
    t.penup()
    t.goto(-100,100)
    t.pendown()
    t.pencolor("magenta")
drawRightTriangle()

t.penup()
t.goto(250, 300)
t.pendown()
t.pencolor("red")
drawRightTriangle()

t.penup()
t.goto(-180,180)
t.pendown()
t.pencolor("purple")
drawRightTriangle()

t.penup()
t.goto(200,-150)
t.pendown()
t.pencolor("pink")
drawRightTriangle()

t.penup()
t.goto(-350,-90)
t.pendown()
t.pencolor("gold")
drawRightTriangle()

t.penup()
t.goto(-350,280)
t.pendown()
t.pencolor("black")
drawRightTriangle()

t.penup()
t.goto(50,250)
t.pendown()
t.pencolor("yellow")
drawRightTriangle()

