import turtle
t=turtle.Turtle()
print("orig.pos:",t.position())

t.setheading(270)
t.pendown()
t.pencolor("green")
t.forward(200)
t.width(10)
t.penup()
x=t.xcor()
y=t.ycor()
print(x,y)
t.pendown()
t.goto(0,0)
t.goto(80,90)
t.penup()
t.goto(0,0)
t.pendown()
t.goto(20,100)
t.penup()
t.goto(0,0)
t.pendown()
t.goto(-40,100)
t.penup()
t.goto(0,0)
t.pendown()
t.goto(-95,90)